# Generated by Django 5.2.17 on 2026-09-29 13:05

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('test_date', models.DateField()),
                ('laboratory_or_hospital', models.CharField(blank=True, max_length=150)),
                ('result_summary', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/', validators=[records.models.validate_report_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='records.familymember')),
            ],
        ),
    ]
