# Generated by Django 5.2.17 on 2026-09-29 13:15

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=150)),
                ('report_date', models.DateField()),
                ('hospital_or_clinic', models.CharField(blank=True, max_length=150)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='medical_reports/', validators=[records.models.validate_report_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='records.familymember')),
            ],
        ),
    ]
