# Generated by Django 5.2.17 on 2026-09-29 13:22

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('hospital_or_clinic', models.CharField(blank=True, max_length=150)),
                ('visit_date', models.DateField()),
                ('reason_for_visit', models.TextField(blank=True)),
                ('diagnosis_or_condition', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('visit_document', models.FileField(blank=True, null=True, upload_to='visit_documents/', validators=[records.models.validate_report_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='records.familymember')),
            ],
        ),
    ]
