# Generated by Django 5.2.17 on 2026-09-29 13:27

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_doctorvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('prescription_date', models.DateField()),
                ('medicines', models.TextField()),
                ('dosage_instructions', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/', validators=[records.models.validate_report_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.familymember')),
            ],
        ),
    ]
