# Generated by Django 5.2.17 on 2026-09-29 13:36

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('policy_number', models.CharField(max_length=150)),
                ('member_id', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('insurance_card', models.FileField(blank=True, null=True, upload_to='insurance_cards/', validators=[records.models.validate_report_file])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='records.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('document_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='medical_documents/', validators=[records.models.validate_report_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='records.familymember')),
            ],
        ),
    ]
